app:
  container_name: app
  restart: always
  build: .
  ports:
    - "3000:3000"
  links:
    - mongo
mongo:
  container_name: mongo
  image: mongo
  restart: always
  expose:
    - "27017"
  volumes:
    - ./data:/data/db
  ports:
    - "27017:27017"